import { Type } from '@sesame/plugin-sdk/schema';
import { AKShareProvider } from './provider.js';
export async function activate(host) { const provider = new AKShareProvider(host), dispose = host.providers.register((await import('./provider.js')).descriptor, provider); return { dispose }; }
export function createTools(host) {
    const { define, string, optional } = host.tools;
    const run = (operation, args, signal, timeoutMs = 120000) => host.environment.executeWorker('worker.js', { operation, ...args }, { signal, timeoutMs });
    return [
        define('akshare_discover','Find and verify a configured/native Python with compatible existing AKShare; readonly reuse first, never download or upgrade shared environments.',{python_path:optional('Configured existing native Python/venv executable')},(args,signal)=>run('discover',{pythonPath:args.python_path},signal)),
        define('akshare_status', 'Inspect optional AKShare environment. Never installs or downloads anything.', {}, (args, signal) => run('status', args, signal)),
        define('akshare_prepare', 'First verify/reuse compatible existing AKShare. If missing, explicitly create an isolated plugin-data Python venv and download pinned AKShare 1.19.1 packages from official PyPI. No global/system package install.', { python_path: optional('Optional native 64-bit Python >=3.11 executable; Linux guest Python is not a macOS host executable') }, (args, signal) => run('prepare', { pythonPath: args.python_path }, signal, 600000)),
        define('akshare_catalog', 'Discover read-only whitelisted AKShare interfaces and their source/units. No arbitrary Python.', {}, () => ({ interfaces: [{ name: 'stock_info_a_code_name', arguments: {}, source: 'AKShare combined exchange catalog' }, { name: 'stock_zh_a_spot_em', arguments: {}, source: 'Eastmoney point-in-time catalog/spot snapshot; not streaming' }, { name: 'stock_zh_a_hist', arguments: { symbol: '6 digit A-share code', period: 'daily', start_date: 'YYYYMMDD', end_date: 'YYYYMMDD', adjust: '|qfq|hfq' }, source: 'Eastmoney', volumeUnit: 'lot (100 shares)' }, { name: 'stock_zh_a_daily', arguments: { symbol: 'sh/sz + 6 digits', start_date: 'YYYYMMDD', end_date: 'YYYYMMDD', adjust: '|qfq|hfq' }, source: 'Sina', volumeUnit: 'share' }], streaming: false, provider: { pluginId: 'sesame/akshare', providerId: 'market' }, connections: [{ id: 'akshare:eastmoney', revision: '1.19.1' }, { id: 'akshare:sina', revision: '1.19.1' }], documentation: 'https://akshare.akfamily.xyz/data/stock/stock.html' })),
        define('akshare_query', 'Call a read-only whitelisted research interface; returns actual source rows or a clear network error. Financial numbers are decimal strings, never synthetic fallback.', { interface: Type.Union(['stock_info_a_code_name', 'stock_zh_a_spot_em', 'stock_zh_a_hist', 'stock_zh_a_daily'].map(value => Type.Literal(value))), arguments: Type.Optional(Type.Record(Type.String(), Type.String())), max_rows: Type.Optional(Type.Integer({ minimum: 1, maximum: 1000, default: 100 })) }, async (args, signal) => { const result = await run('query', { interface: args.interface, arguments: args.arguments }, signal); return { ...result, rows: result.rows.slice(0, args.max_rows ?? 100), totalRows: result.rows.length, truncated: result.rows.length > (args.max_rows ?? 100) }; }),
    ];
}
