import test from 'node:test';import assert from 'node:assert/strict';
import { NativeRunObserver } from '../../optional-api-v1/packages/mt5/backend/run-observer.js';
import { digest, canonical } from '@sesame/plugin-sdk/protocol';
const bytes=Buffer.from('frozen EX5 fixture'),translation={id:'translation',revision:'1',kind:'strategy.translation',schemaVersion:'1.0.0',digest:digest('translation')};
const build={id:'build-fixed',status:'succeeded',conversation_id:'child',owner_run_id:'child-run',ex5_sha256:digest(bytes),manifest_digest:digest('manifest'),translation};const manifest={compiler_sha256:digest('compiler'),files:{}};
function fixture(version='1.1.5'){const rows=new Map(),artifacts=new Map(),requests=new Map(),blobs=new Map();let published=0;const host={plugin:{id:'sesame/mt5',version,digest:digest(version)},records:{list:()=>[]},artifacts:{blob:b=>{const ref={digest:digest(b),size:Buffer.byteLength(b)};blobs.set(ref.digest,Buffer.from(b));return ref;},readBlob:ref=>{const b=blobs.get(ref.digest);assert.equal(digest(b),ref.digest);return b;},read:ref=>{const a=artifacts.get(ref.id);assert.equal(canonical(a.ref),canonical(ref));return structuredClone(a);},list:({offset,limit})=>({items:[...artifacts.values()].slice(offset,offset+limit).map(a=>({ref:a.ref,producer:a.producer})),hasMore:offset+limit<artifacts.size}),publish:input=>{const key=host.plugin.id+input.operationId,fingerprint=digest(input),prior=requests.get(key);if(prior){assert.equal(prior.fingerprint,fingerprint,'host idempotency conflict');return prior.ref;}const ref={id:'artifact-'+(++published),revision:'1',kind:input.manifest.kind,schemaVersion:'1.0.0',digest:digest(input.manifest)};artifacts.set(ref.id,{ref,producer:structuredClone(host.plugin),manifest:structuredClone(input.manifest)});requests.set(key,{fingerprint,ref});return ref;}}};const storage={get:(kind,id)=>rows.get(kind+id),put:(kind,row)=>{rows.set(kind+row.id,structuredClone(row));return row;}};return{host,mt5:{storage},rows,artifacts,requests,observer:()=>new NativeRunObserver(host,{storage}),get published(){return published;}};}
test('repeated runs and plugin upgrade reuse one frozen content reference',()=>{const f=fixture(),first=f.observer().frozenBuild(build,manifest,translation,bytes);assert.deepEqual(f.observer().frozenBuild(build,manifest,translation,bytes),first);f.host.plugin={...f.host.plugin,version:'1.1.6',digest:digest('upgraded')};assert.deepEqual(f.observer().frozenBuild(build,manifest,translation,bytes),first);assert.equal(f.published,1);});
test('pre-index child build survives finalized archive metadata and main-session reuse',()=>{const f=fixture('1.1.3'),old=f.observer().artifact('native-build-'+build.id,'resource',{format:'sesame.mt5.build/1',build,manifest},[translation],{'Strategy.ex5':bytes});f.host.plugin={...f.host.plugin,version:'1.1.6',digest:digest('upgrade')};const archived={...build,archived_artifact:{id:'child-archive'},intermediate_files_removed:true};assert.deepEqual(f.observer().frozenBuild(archived,manifest,translation,bytes),old);assert.deepEqual(f.observer().frozenBuild({...archived,archived_manifest:'retained'},manifest,translation,bytes),old);assert.equal(f.published,1);assert.equal(f.rows.size,3);});
test('changed immutable build, manifest, translation or EX5 cannot silently reuse or create another reference',()=>{for(const change of [()=>[{...build,source_digest:'changed'},manifest,translation,bytes],()=>[build,{...manifest,compiler_sha256:digest('different')},translation,bytes],()=>[build,manifest,{...translation,revision:'2'},bytes],()=>[build,manifest,translation,Buffer.from('different EX5')]]){const f=fixture();f.observer().frozenBuild(build,manifest,translation,bytes);assert.throws(()=>f.observer().frozenBuild(...change()),/冻结构建/);assert.equal(f.published,1);}});
test('legacy candidate with changed immutable bytes is rejected before migration publication',()=>{const f=fixture();f.observer().artifact('native-build-'+build.id,'resource',{format:'sesame.mt5.build/1',build,manifest},[translation],{'Strategy.ex5':Buffer.from('tampered')});assert.throws(()=>f.observer().frozenBuild({...build,intermediate_files_removed:true},manifest,translation,bytes),/EX5/);assert.equal(f.published,1);});
test('legacy migration rejects missing EX5, different translation dependency and conflicting references',()=>{for(const mutate of [a=>a.manifest.blobs=[],a=>a.manifest.dependencies=[{...translation,revision:'different'}]]){const f=fixture();const ref=f.observer().artifact('native-build-'+build.id,'resource',{format:'sesame.mt5.build/1',build,manifest},[translation],{'Strategy.ex5':bytes});mutate(f.artifacts.get(ref.id));assert.throws(()=>f.observer().frozenBuild(build,manifest,translation,bytes),/冻结构建/);assert.equal(f.published,1);}const f=fixture();f.observer().artifact('native-build-'+build.id,'resource',{format:'sesame.mt5.build/1',build,manifest},[translation],{'Strategy.ex5':bytes});f.observer().artifact('another-fixed-ref','resource',{format:'sesame.mt5.build/1',build,manifest},[translation],{'Strategy.ex5':bytes});assert.throws(()=>f.observer().frozenBuild(build,manifest,translation,bytes),/不同冻结引用/);assert.equal(f.published,2);});
test('migration retains original producer identity and indexed foreign references are rejected',()=>{const f=fixture('1.1.3');const ref=f.observer().artifact('native-build-'+build.id,'resource',{format:'sesame.mt5.build/1',build,manifest},[translation],{'Strategy.ex5':bytes});f.host.plugin={...f.host.plugin,version:'1.1.6',digest:digest('upgraded')};f.observer().frozenBuild(build,manifest,translation,bytes);assert.equal(f.artifacts.get(ref.id).producer.version,'1.1.3');f.artifacts.get(ref.id).producer.id='foreign/plugin';assert.throws(()=>f.observer().frozenBuild(build,manifest,translation,bytes),/引用身份/);assert.equal(f.published,1);});

test('foreign producer with the same build ID is never adopted as MT5 evidence',()=>{const f=fixture(),ours=f.host.plugin;f.host.plugin={...ours,id:'foreign/plugin'};const foreign=f.observer().artifact('native-build-'+build.id,'resource',{format:'sesame.mt5.build/1',build,manifest},[translation],{'Strategy.ex5':bytes});f.host.plugin=ours;const actual=f.observer().frozenBuild(build,manifest,translation,bytes);assert.notEqual(actual.id,foreign.id);assert.equal(f.artifacts.get(actual.id).producer.id,'sesame/mt5');});

test('legacy resource scan occurs once across new builds and observer restart',()=>{const f=fixture();let reads=0,lists=0;const read=f.host.artifacts.read,list=f.host.artifacts.list;f.host.artifacts.read=(...a)=>{reads++;return read(...a);};f.host.artifacts.list=(...a)=>{lists++;return list(...a);};for(let i=0;i<25;i++)f.observer().artifact('unrelated-'+i,'resource',{format:'other'},[],{});const legacy={...build,id:'legacy-second'};const ref=f.observer().artifact('native-build-'+legacy.id,'resource',{format:'sesame.mt5.build/1',build:legacy,manifest},[translation],{'Strategy.ex5':bytes});f.observer().frozenBuild(build,manifest,translation,bytes);assert.equal(lists,1);assert.equal(reads,26);for(let i=0;i<20;i++)f.observer().frozenBuild({...build,id:'new-'+i},manifest,translation,bytes);assert.equal(lists,1);assert.equal(reads,26);assert.deepEqual(f.observer().frozenBuild(legacy,manifest,translation,bytes),ref);assert.equal(lists,1);assert.equal(reads,27);});

test('interrupted migration is retried and publication survives index-write failure',()=>{const f=fixture();const legacy=f.observer().artifact('native-build-'+build.id,'resource',{format:'sesame.mt5.build/1',build,manifest},[translation],{'Strategy.ex5':bytes});const read=f.host.artifacts.read;f.host.artifacts.read=()=>{throw Error('read interrupted');};assert.throws(()=>f.observer().frozenBuild(build,manifest,translation,bytes),/interrupted/);assert.equal(f.mt5.storage.get('native_build_migrations','legacy-build-resources-v1'),undefined);f.host.artifacts.read=read;assert.deepEqual(f.observer().frozenBuild(build,manifest,translation,bytes),legacy);const next={...build,id:'new-write-failure'},put=f.mt5.storage.put;let fail=true;f.mt5.storage.put=(kind,row)=>{if(kind==='native_build_inputs'&&fail){fail=false;throw Error('index interrupted');}return put(kind,row);};assert.throws(()=>f.observer().frozenBuild(next,manifest,translation,bytes),/index interrupted/);const count=f.published;f.observer().frozenBuild(next,manifest,translation,bytes);assert.equal(f.published,count);});

test('one-time migration filters foreign list metadata before reading resource content',()=>{const f=fixture(),ours=f.host.plugin;f.host.plugin={...ours,id:'foreign/plugin'};const foreign=f.observer().artifact('unrelated','resource',{format:'other'},[],{});f.host.plugin=ours;const read=f.host.artifacts.read;f.host.artifacts.read=ref=>{assert.notEqual(ref.id,foreign.id);return read(ref);};f.observer().frozenBuild(build,manifest,translation,bytes);});
