import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import { join } from 'node:path';
import { Tester } from '../../optional-api-v1/packages/mt5/backend/tester.js';
const harness=()=>{let row={id:'pass_fixture',build_id:'build_fixture'};const storage={directory:'/unused/long/application/workspace',get:()=>structuredClone(row),put:(_kind,value)=>row=structuredClone(value)};return{tester:new Tester({storage}),row:()=>row}};
test('Tester uses and cleans a private short native runner without touching the application workspace',async()=>{const{tester,row}=harness();let runner;tester.executeInDirectory=async(_pass,_signal,directory)=>{runner=directory;assert.notEqual(directory,tester.storage.directory);await fs.writeFile(join(directory,'owned-file'),'owned');return 'done'};assert.equal(await tester.execute(row(),new AbortController().signal),'done');assert.equal(row().temporary_paths.tester_runner,runner);await assert.rejects(fs.stat(runner),{code:'ENOENT'});});
test('failed preparation cleans its own temporary native runner',async()=>{const{tester,row}=harness();let runner;tester.executeInDirectory=async(_pass,_signal,directory)=>{runner=directory;throw Error('preflight unavailable')};await assert.rejects(tester.execute(row(),new AbortController().signal),/preflight unavailable/);await assert.rejects(fs.stat(runner),{code:'ENOENT'});});
test('unconfirmed process cleanup preserves the owned runner for diagnosis',async t=>{const{tester,row}=harness();let runner;tester.executeInDirectory=async(_pass,_signal,directory)=>{runner=directory;throw Object.assign(Error('job not settled'),{code:'runtime_cleanup_failed'})};await assert.rejects(tester.execute(row(),new AbortController().signal),/job not settled/);t.after(()=>fs.rm(runner,{recursive:true,force:true}));assert.ok((await fs.stat(runner)).isDirectory());});

test('unconfirmed native cleanup survives diagnostic ENOSPC and keeps the pass/job unknown',async t=>{
  const {tmpdir}=await import('node:os'),{digest}=await import('../../optional-api-v1/packages/mt5/backend/support.js');
  const root=await fs.mkdtemp(join(tmpdir(),'tester-diagnostic-failure-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));
  const nativeDirectory=join(root,'native');await fs.mkdir(nativeDirectory);for(const file of ['terminal64.exe','metatester64.exe','MetaEditor64.exe'])await fs.writeFile(join(nativeDirectory,file),'controlled fixture, never executed');
  const bytes=Buffer.from('frozen controlled EX5 fixture'),pass={id:'pass_io_fixture',backtest_id:'bt_fixture',build_id:'build_fixture',status:'queued',connection_version:1,artifact_digest:digest(bytes),config:{symbol:'EURUSD',period:'M1',from_date:'2026-09-25',to_date:'2026-10-09',deposit:100000,currency:'USD',leverage:100,model:4,parameters:{}},risk_limits:{max_risk_per_trade_pct:0.5,max_daily_loss_pct:2,max_open_positions:1,max_lots:'1'}};
  await fs.mkdir(join(root,'mt5/builds/build_fixture/Experts'),{recursive:true});await fs.writeFile(join(root,'mt5/builds/build_fixture/Experts/Strategy.ex5'),bytes);
  const maps={mt5_build:new Map(),mt5_pass:new Map([[pass.id,pass]]),mt5_backtest:new Map([['bt_fixture',{id:'bt_fixture',status:'queued'}]])};const storage={directory:root,get:(k,id)=>structuredClone(maps[k].get(id)),put:(k,row)=>{maps[k].set(row.id,structuredClone(row));return row},list:k=>[...maps[k].values()].map(row=>structuredClone(row)),update(k,id,changes){return this.put(k,{...this.get(k,id),...changes})}};
  const client={workspace:{structuredContent:{workspace:{common_folder:'C:\\users\\fixture\\AppData\\Roaming\\MetaQuotes\\Terminal\\Common'}}},call:async name=>name==='get_trading_account_info'?{structuredContent:{terminal:{server_connected:true},account:{login:'fixture',server:'Fixture-Demo'}}}:{isError:false}};
  const cleanupError=Object.assign(Error('Native Job cleanup not confirmed'),{code:'runtime_cleanup_failed'});let runner;
  const tester=new Tester({storage,native:{directory:nativeDirectory,dataDirectory:nativeDirectory,editor:join(nativeDirectory,'MetaEditor64.exe'),winePrefix:root},official:{config:{version:1,account:{login:'fixture',server:'Fixture-Demo'}},client:()=>client,redact:s=>s}},{runProcess:async(_native,request)=>{runner=request.directory;throw cleanupError;}});
  const originalWrite=fs.writeFile;fs.writeFile=async(path,...args)=>{if(String(path).endsWith('native-paths.json'))throw Object.assign(Error('diagnostic disk full'),{code:'ENOSPC'});return originalWrite(path,...args)};
  try{const result=await tester.start('bt_fixture');assert.equal(result.status,'unknown');assert.equal(result.passes[0].status,'unknown');assert.equal(result.passes[0].cleanup_failed,true);assert.equal(cleanupError.details.diagnosticFailure.code,'ENOSPC');assert.ok((await fs.stat(runner)).isDirectory());assert.equal(await fs.readFile(join(runner,'MQL5/Experts/MT5Agent/build_fixture.ex5'),'utf8'),bytes.toString());}
  finally{fs.writeFile=originalWrite;if(runner)await fs.rm(runner,{recursive:true,force:true});}
});
