import test from 'node:test';
import assert from 'node:assert/strict';
import { MT5MarketProvider } from '../../optional-api-v1/packages/mt5/backend/providers.js';
import { sourceIdentity } from '../../optional-api-v1/packages/mt5/backend/contract-mapping.js';
const server='Fixture-Demo',instrument={sourceId:sourceIdentity(server),instrumentId:'EURUSD'},spec={timeframe:'15m',priceBasis:'bid',adjustment:'none',session:'all',calendarRevision:{status:'unknown'}};
function fixture(){const calls=[],rows=Array.from({length:20},(_,i)=>({time:`2026-10-09T${String(10+Math.floor(i/4)).padStart(2,'0')}:${String(i%4*15).padStart(2,'0')}:00`,open:'1',high:'2',low:'0',close:'1.1',tick_volume:'3'}));const mt5={official:{config:{version:1,account:{server,login:'42'}}},market:{read:async(tool,input)=>{if(tool==='get_trading_account_info')return{terminal:{server_connected:true},account:{server,login:'42'}};calls.push(input);return{history:structuredClone(input.limit<rows.length?rows.slice(0,-1).slice(-input.limit):rows)};}}};const p=new MT5MarketProvider(mt5),context={bindingId:'b',signal:new AbortController().signal};p.bind({},context);return{p,context,calls,rows};}
test('small native tails include the actually observed forming bar, not truncated latest-N closed rows',async()=>{const f=fixture();const r=await f.p.bars({instrument,spec,tailLimit:2,includeForming:true},f.context,true);assert.equal(r.bars.length,2);assert.equal(r.bars.at(-1).isClosed,false);assert.equal(r.bars.at(-1).openTime.value,f.rows.at(-1).time);assert.ok(f.calls[0].limit>f.rows.length);const closed=await f.p.bars({instrument,spec,tailLimit:2,includeForming:false},f.context,true);assert.equal(closed.bars.length,2);assert.ok(closed.bars.every(b=>b.isClosed));});
test('a native response at the complete-window limit is rejected as truncated',async()=>{const f=fixture();f.p.mt5.market.read=async(tool,input)=>tool==='get_trading_account_info'?{terminal:{server_connected:true},account:{server,login:'42'}}:{history:Array.from({length:input.limit},()=>f.rows[0])};await assert.rejects(f.p.bars({instrument,spec,tailLimit:2,includeForming:true},f.context,true),e=>e.code==='SOURCE_UNAVAILABLE');});

test('120 moving native history windows retain no large responses; metadata cache is bounded and expires',async()=>{const f=fixture();for(let i=0;i<120;i++)await f.p.read('get_chart_history',{datetime_from:String(i),datetime_to:String(i+1),limit:100},f.context,1000);assert.equal(f.p.reads.size,0);for(let i=0;i<30;i++)await f.p.read('get_trading_account_info',{key:i},f.context,20);assert.equal(f.p.reads.size,16);await new Promise(r=>setTimeout(r,40));assert.equal(f.p.reads.size,0);f.p.dispose();});
test('same binding consumers own independent pending cancellation, and unbind cannot refill or clear another binding cache',async()=>{const f=fixture(),a=new AbortController(),b=new AbortController();f.p.mt5.market.read=(_tool,_args,signal)=>new Promise((resolve,reject)=>{signal.addEventListener('abort',()=>reject(signal.reason),{once:true});if(_args.finish)resolve({ok:true});});const first=f.p.read('get_chart_history',{}, {...f.context,signal:a.signal}),second=f.p.read('get_chart_history',{}, {...f.context,signal:b.signal});a.abort(new Error('consumer A closed'));await assert.rejects(first,/consumer A/);let settled=false;second.finally(()=>{settled=true;}).catch(()=>{});await new Promise(r=>setImmediate(r));assert.equal(settled,false);const other={bindingId:'other',signal:new AbortController().signal};f.p.bind({},other);await f.p.read('get_trading_account_info',{finish:true},other,1000);assert.equal(f.p.reads.size,1);f.p.unbind({bindingId:'b'});await assert.rejects(second,e=>e.code==='CONNECTION_CHANGED');assert.equal(f.p.reads.size,1);assert.equal(f.p.bindings.get('other').readControllers.size,0);f.p.dispose();assert.equal(f.p.reads.size,0);});
test('late failed or older completed request never deletes or replaces a newer completed cache',async()=>{const f=fixture(),pending=[];f.p.mt5.market.read=()=>new Promise((resolve,reject)=>pending.push({resolve,reject}));const old=f.p.read('metadata',{},f.context,1000),newer=f.p.read('metadata',{},f.context,1000);pending[1].resolve({revision:'new'});await newer;pending[0].resolve({revision:'old'});await old;assert.deepEqual(await f.p.read('metadata',{},f.context,1000),{revision:'new'});const fail=f.p.read('other',{},f.context,1000),success=f.p.read('other',{},f.context,1000);pending[3].resolve({ok:true});await success;pending[2].reject(new Error('older failed'));await assert.rejects(fail);assert.equal(f.p.reads.size,2);f.p.dispose();});
