import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const hostRoot = process.env.SESAME_HOST_ROOT;
test('pipeline tool resolves real artifacts, preserves demo evidence and rejects identity drift', { skip: !hostRoot }, async t => {
  const load = path => import(pathToFileURL(join(hostRoot, path)));
  await load('modules/plugins/sdk-loader.js');
  const { Store } = await load('modules/agent/store.js');
  const { ContractArtifacts } = await load('modules/plugins/artifacts.js');
  const svl = await load('modules/plugins/svl.js');
  const { Type } = await import('@sesame/plugin-sdk/schema');
  const { createTools } = await import('../packages/strategy-authoring/index.js');
  const { createPipelineFixture } = await import('../packages/strategy-authoring/examples/pipeline-fixture.js');
  const directory = mkdtempSync(join(tmpdir(), 'sesame-pipeline-tool-')), store = new Store(directory), api = new ContractArtifacts(store);
  const workspace = join(directory, 'work'); mkdirSync(workspace);
  t.after(() => { store.close(); rmSync(directory, { recursive: true, force: true }); });
  const producer = { id: 'sesame/strategy-authoring', version: '1.1.0', digest: `sha256:${'a'.repeat(64)}` };
  const string = description => Type.String({ description, minLength: 1, maxLength: 20000 });
  const host = { svl, tools: { Type, string, optional: description => Type.Optional(string(description)), define: (name, description, properties, execute) => ({ name, execute }) },
    workspace: { file: async (op, path, content) => { const full = join(workspace, path); assert.ok(full.startsWith(workspace + '/')); if (op === 'read') return readFileSync(full); writeFileSync(full, content); return { path }; } },
    artifacts: { read: ref => api.read(ref), blob: bytes => api.blob(bytes), readBlob: blob => api.readBlob(blob), publish: value => api.publish(producer, value) } };
  const tools = new Map(createTools(host).map(tool => [tool.name, tool]));
  const call = (name, args) => tools.get(name).execute(args);
  const sourceBytes = readFileSync(new URL('../packages/strategy-authoring/examples/function-threshold.svl.json', import.meta.url));
  writeFileSync(join(workspace, 'source.json'), sourceBytes);
  const source = await call('strategy_publish', { operation_id: 'demo-source', source_path: 'source.json', title: 'Demo function source', change_summary: 'Offline fixture' });
  assert.equal(api.read(source.ref).manifest.content.languageVersion, '1.1.0');
  assert.equal(source.ref.schemaVersion, '1.0.0');
  const publish = (kind, operationId) => api.publish(producer, { operationId, manifest: { kind, schemaVersion: '1.0.0', content: { type: 'fictional-pipeline-fixture', provenance: { kind: 'demo' } }, blobs: [], dependencies: [], provenance: { kind: 'demo', references: [] } } });
  const evidence = publish('resource', 'demo-evidence'), targetProfile = publish('strategy.target', 'demo-target');
  const fixture = createPipelineFixture({ strategySource: source.ref, strategyId: JSON.parse(sourceBytes).strategyId, evidence, targetProfile });
  writeFileSync(join(workspace, 'fixture.json'), JSON.stringify(fixture));
  const result = await call('strategy_pipeline', { fixture_path: 'fixture.json', output_path: 'result.json', operation_id: 'demo-evaluation' });
  assert.equal(result.validationScope, 'fixed-input-pipeline-evaluation');
  assert.equal(result.nativeEngineExecuted, false);
  assert.equal(result.executionPlan.status, 'ready');
  assert.equal(result.executionPlan.intents.length, 2);
  const saved = api.read(result.evidence);
  assert.equal(saved.manifest.provenance.kind, 'demo');
  assert.ok(saved.manifest.dependencies.some(ref => ref.digest === source.ref.digest));
  assert.ok(saved.manifest.dependencies.some(ref => ref.digest === targetProfile.digest));
  assert.equal(JSON.parse(readFileSync(join(workspace, 'result.json'))).executionPlan.digest, result.executionPlan.digest);
  const repeated = await call('strategy_pipeline', { fixture_path: 'fixture.json', operation_id: 'demo-evaluation' });
  assert.deepEqual(repeated.evidence, result.evidence);
  const drift = structuredClone(fixture); drift.scope.strategyId = 'different-strategy';
  writeFileSync(join(workspace, 'drift.json'), JSON.stringify(drift));
  await assert.rejects(call('strategy_pipeline', { fixture_path: 'drift.json' }), /ownership differs/);
  const forged = structuredClone(fixture); forged.target.strategySource.digest = `sha256:${'0'.repeat(64)}`;
  writeFileSync(join(workspace, 'forged.json'), JSON.stringify(forged));
  await assert.rejects(call('strategy_pipeline', { fixture_path: 'forged.json' }), /artifact|reference|digest|identity/i);
});
