import test from 'node:test';
import assert from 'node:assert/strict';
import { AKShareProvider, descriptor, mapBar, wall } from '../provider.js';
import { validateFinancialData, validateRead } from '@sesame/plugin-sdk/protocol';
const fixture = () => {
    const calls = [], host = { environment: { executeWorker: async (entry, payload) => { calls.push(payload); return { observedAt: 1728000000000, akshareVersion: '1.19.1', interface: payload.interface, rows: payload.interface === 'stock_info_a_code_name' ? [{ code: '000001', name: '平安银行' }, { code: '600000', name: '浦发银行' }] : ['02', '03', '04'].map(d => ({ '日期': '2024-09-' + d, '开盘': '10.00', '最高': '11.00', '最低': '9.00', '收盘': '10.50', '成交量': '9007199254740993' })) }; } } }, provider = new AKShareProvider(host), context = { bindingId: 'test-binding' };
    provider.bind({}, context);
    return { provider, context, calls };
};
const input = () => ({ instrument: { sourceId: 'akshare:eastmoney:a-share', instrumentId: '000001' }, spec: { timeframe: '1d', priceBasis: 'last', adjustment: 'none', session: 'regular', calendarRevision: { status: 'unknown' } }, range: { from: { basis: 'wall', authority: 'Asia/Shanghai', value: '2024-09-01T00:00:00' }, to: { basis: 'wall', authority: 'Asia/Shanghai', value: '2024-10-01T00:00:00' } }, page: { limit: 1 } });
test('history is actual-source-labelled, paged immutable and financially valid', async () => { const { provider, context, calls } = fixture(), query = input(); const first = await provider.queryBars(query, context); validateFinancialData(first.data); validateRead(first, { ...descriptor, pluginId: 'sesame/akshare' }, 'fixture'); assert.equal(first.data.page.items.length, 1); assert.equal(first.data.page.items[0].volume.real.value.value, '9007199254740993'); assert.equal(first.data.page.items[0].volume.real.value.unit, 'lot'); assert.equal(first.meta.source.interface, 'stock_zh_a_hist'); assert.equal(first.meta.freshness, 'delayed'); assert.equal(first.data.coverage.complete, false); const second = await provider.queryBars({ ...query, page: { limit: 1, cursor: first.data.page.nextCursor } }, context); assert.equal(calls.length, 1); assert.equal(second.data.page.snapshotId, first.data.page.snapshotId); assert.notEqual(second.data.page.items[0].id, first.data.page.items[0].id); await assert.rejects(provider.queryBars({ ...query, spec: { ...query.spec, adjustment: 'qfq' }, page: { limit: 1, cursor: first.data.page.nextCursor } }, context), /Cursor/); provider.unbind(context); await assert.rejects(provider.queryBars(query, context), /Binding/); });
test('catalog pagination and explicit source/version binding', async () => { const { provider, context } = fixture(); const a = await provider.searchInstruments({ query: '', page: { limit: 1 } }, context), b = await provider.searchInstruments({ query: '', page: { limit: 1, cursor: a.data.nextCursor } }, context); assert.equal(a.data.items[0].symbol, '000001'); assert.equal(b.data.items[0].symbol, '600000'); assert.equal(b.data.nextCursor, null); assert.throws(() => provider.bind({ connection: { id: 'akshare:sina', revision: 'wrong' } }, context), /Connection/); assert.ok(!descriptor.capabilities.some(c => c.includes('subscribe')));
    const replay = provider.bind({connection:{id:'akshare:sina',revision:'1.19.1'}}, {bindingId:'restored'});
    assert.equal(replay.sourceIds[0], 'akshare:sina:a-share', 'persisted exact connection restores source without guessing'); });
test('source time, missing fields and bar revisions are conservative', () => { assert.equal(wall({ basis: 'utc', unixMs: 0 }), '1970-01-01T08:00:00'); assert.throws(() => wall({ basis: 'wall', authority: 'broker', value: '2024-09-01T00:00:00' })); const row = { '日期': '2024-09-02', '开盘': '10', '最高': '11', '最低': '9', '收盘': '10', '成交量': null }; const bar = mapBar(row, 'eastmoney', 'series', 0); assert.equal(bar.isClosed, false); assert.equal(bar.volume.real.status, 'unknown'); assert.equal(bar.volume.tick.status, 'unsupported'); const { provider } = fixture(); assert.equal(provider.revise(bar).revision, '1'); assert.equal(provider.revise({ ...bar }).revision, '1'); assert.equal(provider.revise({ ...bar, close: '11' }).revision, '2'); assert.throws(() => mapBar({ ...row, '收盘': 10 }, 'eastmoney', 'series', 0), /decimal/); });
test('network failures are never converted to fabricated rows', async () => { const { provider, context } = fixture(); provider.host.environment.executeWorker = async () => { throw Error('network unavailable'); }; await assert.rejects(provider.queryBars(input(), context), /network unavailable/); });
