import test from 'node:test';
import assert from 'node:assert/strict';
import { AKShareProvider, descriptor, mapBar, wall } from '../provider.js';
import { validateFinancialData, validateRead } from '@sesame/plugin-sdk/protocol';
const fixture = () => {
    const calls = [], host = { environment: { executeWorker: async (entry, payload) => { calls.push(payload); return { observedAt: 1728000000000, akshareVersion: '1.19.1', interface: payload.interface, rows: payload.interface === 'stock_info_a_code_name' ? [{ code: '000001', name: '平安银行' }, { code: '600000', name: '浦发银行' }] : ['02', '03', '04'].map(d => ({ '日期': '2024-09-' + d, '开盘': '10.00', '最高': '11.00', '最低': '9.00', '收盘': '10.50', '成交量': '9007199254740993' })) }; } } }, provider = new AKShareProvider(host), context = { bindingId: 'test-binding' };
    provider.bind({}, context);
    return { provider, context, calls };
};
const input = () => ({ instrument: { sourceId: 'akshare:eastmoney:a-share', instrumentId: '000001' }, spec: { timeframe: '1d', priceBasis: 'last', adjustment: 'none', session: 'regular', calendarRevision: { status: 'unknown' } }, range: { from: { basis: 'wall', authority: 'Asia/Shanghai', value: '2024-09-01T00:00:00' }, to: { basis: 'wall', authority: 'Asia/Shanghai', value: '2024-10-01T00:00:00' } }, page: { limit: 1 } });
test('history is actual-source-labelled, paged immutable and financially valid', async () => { const { provider, context, calls } = fixture(), query = input(); const first = await provider.queryBars(query, context); validateFinancialData(first.data); validateRead(first, { ...descriptor, pluginId: 'sesame/akshare' }, 'fixture'); assert.equal(first.data.page.items.length, 1); assert.equal(first.data.page.items[0].volume.real.value.value, '9007199254740993'); assert.equal(first.data.page.items[0].volume.real.value.unit, 'lot'); assert.equal(first.meta.source.interface, 'stock_zh_a_hist'); assert.equal(first.meta.freshness, 'delayed'); assert.equal(first.data.coverage.complete, false); const second = await provider.queryBars({ ...query, page: { limit: 1, cursor: first.data.page.nextCursor } }, context); assert.equal(calls.length, 1); assert.equal(second.data.page.snapshotId, first.data.page.snapshotId); assert.notEqual(second.data.page.items[0].id, first.data.page.items[0].id); await assert.rejects(provider.queryBars({ ...query, spec: { ...query.spec, adjustment: 'forward' }, page: { limit: 1, cursor: first.data.page.nextCursor } }, context), /Cursor/); provider.unbind(context); await assert.rejects(provider.queryBars(query, context), /Binding/); });
test('catalog pagination and explicit source/version binding', async () => { const { provider, context } = fixture(); const a = await provider.searchInstruments({ query: '', page: { limit: 1 } }, context), b = await provider.searchInstruments({ query: '', page: { limit: 1, cursor: a.data.nextCursor } }, context); assert.equal(a.data.items[0].symbol, '000001'); assert.equal(b.data.items[0].symbol, '600000'); assert.equal(b.data.nextCursor, null); assert.throws(() => provider.bind({ connection: { id: 'akshare:sina', revision: 'wrong' } }, context), /Connection/); assert.ok(descriptor.capabilities.includes('bars.subscribe'));assert.ok(descriptor.capabilities.includes('quotes.subscribe'));
    const replay = provider.bind({connection:{id:'akshare:sina',revision:'1.19.1'}}, {bindingId:'restored'});
    assert.equal(replay.sourceIds[0], 'akshare:sina:a-share', 'persisted exact connection restores source without guessing'); });
test('source time, missing fields and bar revisions are conservative', () => { assert.equal(wall({ basis: 'utc', unixMs: 0 }), '1970-01-01T08:00:00.000'); assert.throws(() => wall({ basis: 'wall', authority: 'broker', value: '2024-09-01T00:00:00' })); const row = { '日期': '2024-09-02', '开盘': '10', '最高': '11', '最低': '9', '收盘': '10', '成交量': null }; const bar = mapBar(row, 'eastmoney', 'series', 0); assert.equal(bar.isClosed, false); assert.equal(bar.volume.real.status, 'unknown'); assert.equal(bar.volume.tick.status, 'unsupported'); const { provider } = fixture(); assert.equal(provider.revise(bar).revision, '1'); assert.equal(provider.revise({ ...bar }).revision, '1'); assert.equal(provider.revise({ ...bar, close: '11' }).revision, '2'); assert.throws(() => mapBar({ ...row, '收盘': 10 }, 'eastmoney', 'series', 0), /decimal/); });
test('network failures are never converted to fabricated rows', async () => { const { provider, context } = fixture(); provider.host.environment.executeWorker = async () => { throw Error('network unavailable'); }; await assert.rejects(provider.queryBars(input(), context), /network unavailable/); });

test('quote observations and real daily-tail streams are explicit and close cleanly',async()=>{const{provider,context}=fixture();const instrument=input().instrument;provider.host.environment.executeWorker=async(_entry,payload)=>({observedAt:Date.now(),akshareVersion:'1.19.1',interface:payload.interface,rows:[{item:'最新',value:'10.25'},{item:'buy_1',value:'10.24'},{item:'sell_1',value:'10.26'}]});const stream=await provider.subscribeQuotes({instruments:[instrument]},context);assert.equal(stream.snapshot.quotes[0].last.value,'10.25');assert.equal(stream.snapshot.meta.freshness,'unknown');assert.equal(stream.snapshot.quotes[0].native.observationTimeOnly,true);assert.equal(stream.position.seq,'0');stream.ready(()=>{throw Error('should not poll before interval')});await stream.close();assert.equal(provider.streams.size,0);await assert.rejects(provider.subscribeQuotes({instruments:[instrument],resumeToken:'old'},context));});

test('daily subscription tail includes the newest rows beyond the first history page',async()=>{const{provider,context,calls}=fixture();const rows=Array.from({length:2501},(_,i)=>({'日期':new Date(Date.UTC(2019,0,1)+i*86400000).toISOString().slice(0,10),'开盘':'10','最高':'11','最低':'9','收盘':'10','成交量':'100'}));provider.host.environment.executeWorker=async(_entry,payload)=>{calls.push(payload);return{observedAt:Date.now(),akshareVersion:'1.19.1',interface:payload.interface,rows}};const stream=await provider.subscribeBars({...input(),tailLimit:2000},context);assert.equal(stream.snapshot.bars.length,2000);assert.equal(stream.snapshot.bars.at(-1).openTime.value.slice(0,10),rows.at(-1)['日期']);assert.equal(calls.length,1,'immutable cursor pages reuse one actual source snapshot');await stream.close();});


test('Tencent history routes Shanghai, Shenzhen and both Beijing code generations correctly',async()=>{for(const [code,symbol] of [['600519','sh600519'],['688001','sh688001'],['000001','sz000001'],['300750','sz300750'],['430047','bj430047'],['830799','bj830799'],['920002','bj920002']]){const{provider,context}=fixture();provider.bind({connection:{id:'akshare:tencent',revision:'1.19.1'}},context);let request;provider.host.environment.executeWorker=async(_entry,payload)=>{request=payload;return{observedAt:Date.now(),akshareVersion:'1.19.1',interface:payload.interface,rows:[]}};await provider.queryBars({...input(),instrument:{sourceId:'akshare:tencent:a-share',instrumentId:code}},context);assert.equal(request.interface,'stock_zh_a_hist_tx');assert.equal(request.arguments.symbol,symbol);}});


test('backward pages, exact fractional bounds and Bar identity preserve the daily contract',async()=>{
 const {provider,context}=fixture(),query=input();try{
  const first=await provider.queryBars({...query,direction:'backward'},context);assert.equal(first.data.page.items[0].openTime.value,'2024-09-04T09:30:00');assert.deepEqual(first.data.instrument,query.instrument);assert.deepEqual(first.data.spec,query.spec);assert.ok(first.data.coverage.observedRange);assert.ok(Array.isArray(first.data.coverage.gaps));assert.equal(first.data.page.items[0].isClosed,false);assert.equal(first.data.page.items[0].closure,'unknown');assert.equal(first.data.page.items[0].turnover.status,'unknown');
  const second=await provider.queryBars({...query,direction:'backward',page:{limit:1,cursor:first.data.page.nextCursor}},context);assert.equal(second.data.page.items[0].openTime.value,'2024-09-03T09:30:00');assert.equal(second.data.page.items[0].closure,'source');
  const range={from:{basis:'utc',unixMs:Date.parse('2024-09-04T09:30:00.001+08:00')},to:query.range.to};assert.equal((await provider.queryBars({...query,range},context)).data.page.items.length,0);
  const stream=await provider.subscribeBars({...query,tailLimit:2000,includeForming:false},context);try{assert.equal(stream.snapshot.bars.length,2);assert.ok(stream.snapshot.bars.every(bar=>bar.isClosed));assert.deepEqual(stream.snapshot.instrument,query.instrument);assert.deepEqual(stream.snapshot.spec,query.spec);assert.ok(stream.snapshot.coverage);}finally{await stream.close();}
 }finally{provider.dispose();}
});

test('source closure survives a narrower response and cache eviction while prices can be corrected',async()=>{
 const {provider,context}=fixture(),query=input();try{await provider.queryBars({...query,page:{limit:10}},context);provider.revisions.clear();provider.host.environment.executeWorker=async()=>({observedAt:Date.now(),akshareVersion:'1.19.1',interface:'stock_zh_a_hist',rows:[{'日期':'2024-09-03','开盘':'10','最高':'11','最低':'9','收盘':'10.9','成交量':null}]});const result=await provider.queryBars({...query,includeForming:false},context);assert.equal(result.data.page.items[0].close,'10.9');assert.equal(result.data.page.items[0].isClosed,true);assert.equal(result.data.page.items[0].closure,'source');assert.equal(result.data.page.items[0].volume.default,'none');}finally{provider.dispose();}
});
